# wrangler.toml
name = "reviewindex"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[functions]]
include = ["functions/**/*.js"]

[functions.assets]
bucket = ""
include = ["*.html", "*.css", "*.js"]
exclude = ["node_modules", "*.ts"]

[env.production]
GITHUB_TOKEN = "@github_token"
SITE_URL = "https://reviewindex.pages.dev"
